version: '3.9'
services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    networks:
      - web
    depends_on:
      - app
  app:
    image: php:7.4-fpm
    volumes:
      - ./html:/var/www/html
    networks:
      - web