version: '3.9'
services:
  image: db
  container_name: mssql2017
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: db
    MYSQL_USER: user
    MYSQL_PASSWORD: password
  volumes:
    - "../volumes/mssqlsrv2017:/var/opt/mssql/data" 