version: '3.9'
services:

  user.data:
    image: redis:6.2.1
    networks:
      - apis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - apis
      - backend
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 20

  sql.data:
    # image: sql-data
    build:
      context: ./
      dockerfile: ./appscore/Database/Dockerfile
    volumes:
      - "../volumes/mssqlsrv2017:/var/opt/mssql/data" 
    networks:
      - apis
      - db
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "sqlcmd", "-S", "localhost", "-U", "sa", "-P", "root", "-Q", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  service-api-applicants:
    image: hugolmty/applicants-api:latest
    environment:
      - ConnectionString=Server=sql.data;User=sa;Password=Pass@word;Database=dotnetgigs.applicants;
      - HostRabbitmq=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend
      - db
      - apis
    ports:
      - "8081:80"

  service-api-jobs:
    image: hugolmty/jobs-api:latest
    environment:
      - ConnectionString=Server=sql.data;User=sa;Password=Pass@word;Database=dotnetgigs.jobs;
      - HostRabbitmq=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend
      - apis
    ports:
      - "8083:80"

  service-api-identity:
    image: hugolmty/identity-api:latest
    environment:
      - RedisHost=user.data:6379
      - HostRabbitmq=rabbitmq
      - ConnectionString=Server=sql.data;User=sa;Password=Pass@word;Database=dotnetgigs.identity;      
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - backend
      - apis
    ports:
      - "8084:80"

  web:
    image: web
    environment:
      - HostRabbitmq=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - service-api-applicants
      - service-api-jobs
      - service-api-identity
    networks:
      - frontend
      - backend
      - apis
      - db
    ports:
      - "80:80"

networks:
  frontend:
    name: frontend
  apis:
    name: apis
  backend:
    name: backend
  db:
    name: db
